name: jobs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  php:
    name: PHP tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["7.4", "8.0"]
        composer-version: [1, 2]

    steps:
      - uses: actions/checkout@v3
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          version: ${{ matrix.composer-version }}
          php_extensions: simplexml soap
      - name: Run easy coding standard
        run: vendor/bin/ecs check
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm i
      - run: npx prettier --check .
  release:
    name: Release
    needs: [php, prettier]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install && npx semantic-release
